// @ts-check
import { defineConfig } from 'astro/config';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE = 'https://girlgeekacademy.com';

/** Old WordPress post URLs were /<slug>/ — send them to /news/<slug>/. */
const newsRedirects = Object.fromEntries(
	readdirSync(new URL('./src/content/news/', import.meta.url))
		.filter((f) => f.endsWith('.md'))
		.flatMap((f) => {
			const slug = f.replace(/\.md$/, '');
			const src = readFileSync(new URL(`./src/content/news/${f}`, import.meta.url), 'utf8');
			const legacy = src.match(/^legacySlug:\s*"?([^"\n]+)"?$/m)?.[1];
			return [slug, legacy].filter(Boolean).map((old) => [`/${old}`, `/news/${slug}/`]);
		}),
);

/**
 * Old URLs → new pages. Astro writes a refresh page for each one, and the build
 * also turns every entry into a real 301 in dist/.htaccess (see launchFiles below).
 */
const redirects = {
	'/work-with-us/schools': '/work-with-us/#schools',
	'/work-with-us/libraries': '/work-with-us/#libraries',
	'/work-with-us/corporates': '/work-with-us/#corporates',
	'/work-with-us/women-in-tech': '/work-with-us/#women-in-tech',
	'/work-with-us/conferences': '/work-with-us/#conferences',
	'/work-with-us/government': '/work-with-us/#government',
	'/work-with-us/media': '/work-with-us/#media',
	'/case-studies/missmakescode-teacher-training': '/missmakescode/#impact',
	'/blog': '/news/',
	// Programs now offered to commission rather than open sign-up
	'/microsoft': '/case-studies/microsoft-mondays/',
	'/high-school': '/shehacksswift/',
	// Old WordPress pages
	'/contact': '/work-with-us/',
	'/schoolholidays': '/shehacksswift/',
	'/stockphotos': '/about/',
	'/team': '/about/#team',
	'/team/sarah-moran': '/about/sarah-moran/',
	'/team/lisy-kane': '/about/lisy-kane/',
	'/team/amanda-watts': '/about/amanda-watts/',
	'/team/april-staines': '/about/april-staines/',
	'/team/tammy-butow': '/about/#team',
	...newsRedirects,
};

/** WordPress-only paths with no Astro page. These exist only as 301s in dist/.htaccess. */
const serverOnlyRedirects = [
	['^wp-content/uploads/2023/06/GGA-Diversity-in-STEM-review-submission-FINAL-?\\.pdf$', '/reports/GGA-Diversity-in-STEM-review-submission-FINAL.pdf'],
	['^feed/?$', '/news/'],
	['^(category|tag)/.*$', '/news/'],
	['^author/.*$', '/about/'],
	['^product/.*$', '/shop/'],
	['^(cart|checkout|my-account)(/.*)?$', '/shop/'],
];

/** Pages built but left out of the sitemap. */
const sitemapExclude = new Set(['/shop/thank-you/']);

const escapeRegex = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * Writes dist/sitemap.xml and dist/.htaccess after every build.
 * No dependencies: it scans the built pages, skipping redirect pages.
 */
function launchFiles() {
	return {
		name: 'gga-launch-files',
		hooks: {
			'astro:build:done': ({ dir }) => {
				const out = dir instanceof URL ? fileURLToPath(dir) : String(dir);

				const pages = [];
				const walk = (folder) => {
					for (const name of readdirSync(folder)) {
						const path = join(folder, name);
						if (statSync(path).isDirectory()) walk(path);
						else if (name === 'index.html') {
							const html = readFileSync(path, 'utf8');
							if (html.includes('http-equiv="refresh"') || html.includes('content="noindex')) continue;
							const rel = relative(out, dirname(path)).split(sep).join('/');
							const url = rel ? `/${rel}/` : '/';
							if (!sitemapExclude.has(url)) pages.push(url);
						}
					}
				};
				walk(out);
				const entries = pages.sort().map((url) => `  <url><loc>${SITE}${url}</loc></url>`);
				writeFileSync(
					join(out, 'sitemap.xml'),
					`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries.join('\n')}\n</urlset>\n`,
				);

				const rules = [
					...Object.entries(redirects).map(
						([from, to]) => `RewriteRule ^${escapeRegex(from.replace(/^\/+|\/+$/g, ''))}/?$ ${to} [R=301,NE,L]`,
					),
					...serverOnlyRedirects.map(([pattern, to]) => `RewriteRule ${pattern} ${to} [R=301,NE,L]`),
				];
				writeFileSync(
					join(out, '.htaccess'),
					[
						'# Generated by astro.config.mjs on every build. Edit the redirects there, not here.',
						'ErrorDocument 404 /404.html',
						'<IfModule mod_rewrite.c>',
						'RewriteEngine On',
						...rules,
						'</IfModule>',
						'',
					].join('\n'),
				);
			},
		},
	};
}

// https://astro.build/config
export default defineConfig({
	site: SITE,
	redirects,
	integrations: [launchFiles()],
});
