name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Install SSH key
        uses: shimataro/ssh-key-action@87a8f06
        with:
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          name: gga_website_deploy
          known_hosts: ${{ env.DEPLOY_SSH_HOST }}
          if_key_exists: fail

      - name: rsync deploy
        env:
        run: |
          rsync -avz --dry-run \
            -e "ssh -i ~/.ssh/gga_website_deploy -o StrictHostKeyChecking=yes" \
            ./dist/ \
            "${{ env.DEPLOY_SSH_USER }}@${{ env.DEPLOY_SSH_HOST }}:~/public_html_new/"
